=== sergiomateos1daw/LMSGI_UD4/MODULOS CFGS/modulos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:annotation>
  <xs:documentation xml:lang="Es-es">
    Esquema para Modulos
    <fecha>30/01/2022</fecha>
    <autor>Sergio Mateos Puerta</autor>
  </xs:documentation>
</xs:annotation>
  <xs:element name="modulos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="modulo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="modulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="contenidos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="contenidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ud1"/>
        <xs:element ref="ud2"/>
        <xs:element ref="ud3"/>
        <xs:element ref="ud4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ud1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ud2">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ud3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ud4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo"/>
        <xs:element ref="descripcion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo" type="xs:string"/>
  <xs:element name="descripcion" type="xs:string"/>
</xs:schema>

=== sergiomateos1daw/LMSGI_UD4/MODULOS CFGS/modulos copy.xml
<?xml version="1.0" encoding="UTF-8"?> 
<modulos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="modulos.xsd">
    <modulo>
        <nombre>Programacion</nombre>
        <contenidos>
            <ud1>
                <tipo>Programar con bloques</tipo>
                <descripcion>Se programa a un nivel m√°s sencillo</descripcion>
            </ud1>
            <ud2>
                <tipo>Programar en arduino</tipo>
                <descripcion>Programar con el lenguaje arduino</descripcion>
            </ud2>
            <ud3>
                <tipo>Programar en JavaFX</tipo>
                <descripcion>Programar con JavaFX</descripcion>
            </ud3>
            <ud4>
                <tipo>Programacion en JavaFX</tipo>
                <descripcion>Programar en javaFX con mas de una clase</descripcion>
            </ud4>
        </contenidos>
    </modulo>
    <modulo>
        <nombre>LMGSI</nombre>
        <contenidos>
            <ud1>
                <tipo>HTML</tipo>
                <descripcion>Programar en HTML</descripcion>
            </ud1>
            <ud2>
                <tipo>CSS</tipo>
                <descripcion>Programar enCSS</descripcion>
            </ud2>
            <ud3>
                <tipo>XML</tipo>
                <descripcion>Programar en XML</descripcion>
            </ud3>
            <ud4>
                <tipo>XML DTD XSD</tipo>
                <descripcion>Hacer xml con dtd y xsd</descripcion>
            </ud4>
        </contenidos>
    </modulo>
    <modulo>
        <nombre>Base de datos</nombre>
        <contenidos>
            <ud1>
                <tipo>Esquema Entidad relacion</tipo>
                <descripcion>Bases del esquema entidad relacion</descripcion>
            </ud1>
            <ud2>
                <tipo>Esquema Entidad relacion</tipo>
                <descripcion>Convertir problemas en esquema entidad relacion</descripcion>
            </ud2>
            <ud3>
                <tipo>Modelo relacional</tipo>
                <descripcion>Convertir esquema entidad relacion en Modelo relacional</descripcion>
            </ud3>
            <ud4>
                <tipo>Lenguaje SQL</tipo>
                <descripcion>Implementar modelo relacion en SQL</descripcion>
            </ud4>
        </contenidos>
    </modulo>
</modulos>
