=== sergiomateos1daw/LMSGI_UD4/LIBRERIA/lista_libros.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT libreria (libro*)>
<!ELEMENT libro (autores, titulo, editorial, fechaPublicacion, ISBN)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (apellido1, apellido2, nombre)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

=== sergiomateos1daw/LMSGI_UD4/LIBRERIA/lista_libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "lista_libros.dtd">
<libreria>
    <libro>
        <autores>
            <autor>
                <apellido1>Ramírez</apellido1>
                <apellido2>Sanchez</apellido2>
                <nombre>José Antonio</nombre>
            </autor>
        </autores>
        <titulo>El sol y la luna</titulo>
        <ISBN>0199535566</ISBN>
        <editorial>Anaya</editorial>
        <fechaPublicacion>20/10/2000</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Mateos</apellido1>
                <apellido2>Rios</apellido2>
                <nombre>Marcos</nombre>
            </autor>
        </autores>
        <titulo>Buscando a Marcos</titulo>
        <ISBN>0199535567</ISBN>
        <editorial>Anaya</editorial>
        <fechaPublicacion>12/5/2015</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Marquez</apellido1>
                <apellido2>Mendoza</apellido2>
                <nombre>Alberto</nombre>
            </autor>
        </autores>
        <titulo>El parque de mi casa</titulo>
        <ISBN>0199535568</ISBN>
        <editorial>Safe</editorial>
        <fechaPublicacion>24/3/2014</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Linares</apellido1>
                <apellido2>Ossorio</apellido2>
                <nombre>Airam</nombre>
            </autor>
        </autores>
        <titulo>Un canario en España</titulo>
        <ISBN>0199535569</ISBN>
        <editorial>Volcan</editorial>
        <fechaPublicacion>22/10/2004</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
    <libro>
        <autores>
            <autor>
                <apellido1>Rios</apellido1>
                <apellido2>Fernandez</apellido2>
                <nombre>Anotio Juan</nombre>
            </autor>
        </autores>
        <titulo>El pago pendiente</titulo>
        <ISBN>0199535570</ISBN>
        <editorial>JerezBook</editorial>
        <fechaPublicacion>23/12/2018</fechaPublicacion>
    </libro>
</libreria>
