=== sergiomateos1daw/LMSGI_UD4/LIBRERIA/CASO REAL/kindle.dtd
<?xml encoding="utf-8"?>
<!ELEMENT libreria (libro)+>
    <!ATTLIST libreria
        xmlns CDATA #FIXED ''>
<!ELEMENT libro (titulo,autores,idioma,editorial,ASIN,longitudImpresion,fechaPublicacion)>
<!ATTLIST libro
    xmlns CDATA #FIXED ''>

<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo
    xmlns CDATA #FIXED ''>

<!ELEMENT autores (autor)>
<!ATTLIST autores
    xmlns CDATA #FIXED ''>

<!ELEMENT idioma (#PCDATA)>
<!ATTLIST idioma
    xmlns CDATA #FIXED ''>

<!ELEMENT editorial (#PCDATA)>
<!ATTLIST editorial
    xmlns CDATA #FIXED ''>

<!ELEMENT ASIN (#PCDATA)>
<!ATTLIST ASIN
    xmlns CDATA #FIXED ''>

<!ELEMENT longitudImpresion (#PCDATA)>
<!ATTLIST longitudImpresion
    xmlns CDATA #FIXED ''>

<!ELEMENT fechaPublicacion (#PCDATA)>
<!ATTLIST fechaPublicacion
    xmlns CDATA #FIXED ''>

<!ELEMENT autor (apellido1,nombre)>
<!ATTLIST autor
    xmlns CDATA #FIXED ''>

<!ELEMENT apellido1 (#PCDATA)>
<!ATTLIST apellido1
    xmlns CDATA #FIXED ''>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
    xmlns CDATA #FIXED ''>

=== sergiomateos1daw/LMSGI_UD4/LIBRERIA/CASO REAL/kindleDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "kindle.dtd">
<libreria>
    <libro>
        <titulo>Pista helada (Tracy Crosswhite nº 7)</titulo>
        <autores>
            <autor>
                <apellido1>Dugoni</apellido1>
                <nombre> Robert</nombre>
            </autor>
        </autores>
        <idioma>Español</idioma>
        <editorial>Amazon Crossing</editorial>
        <ASIN>B09CGBWXJF</ASIN>
        <longitudImpresion>396</longitudImpresion>
        <fechaPublicacion>28 diciembre 2021</fechaPublicacion>
    </libro>
    <libro>
        <titulo>Mi vida entre manzanas rojas</titulo>
        <autores>
            <autor>
                <apellido1>Tello</apellido1>
                <nombre>Lourdes</nombre>
            </autor>
        </autores>
        <idioma>Español</idioma>
        <editorial>Amazon Crossing</editorial>
        <ASIN>B0966T7MS3</ASIN>
        <longitudImpresion>282</longitudImpresion>
        <fechaPublicacion>29 mayo 2021</fechaPublicacion>
    </libro>
    <libro>
        <titulo>Lujuria. : Un increíble thriller adictivo</titulo>
        <autores>
            <autor>
                <apellido1>Escobar</apellido1>
                <nombre>Mario</nombre>
            </autor>
        </autores>
        <idioma>Español</idioma>
        <editorial>Amazon Crossing</editorial>
        <ASIN>B08YRSWT6W</ASIN>
        <longitudImpresion>125</longitudImpresion>
        <fechaPublicacion>14 mayo 2021</fechaPublicacion>
    </libro>
</libreria>
