=== sergiomateos1daw/LMSGI_UD4/CONCESIONARIO/CASO REAL/flexicar.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
  <xs:documentation xml:lang="Es-es">
    Esquema para la web FlexiCar
    <fecha>28/01/2022</fecha>
    <autor>Sergio Mateos</autor>
  </xs:documentation>
</xs:annotation>
  <xs:element name="coches">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="coche">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:unsignedByte" />
              <xs:element name="marca" type="xs:string" />
              <xs:element name="modelo" type="xs:string" />
              <xs:element name="potencia" type="xs:string" />
              <xs:element name="kms" type="xs:string" />
              <xs:element name="plazas" type="xs:unsignedByte" />
              <xs:element name="puertas" type="xs:unsignedByte" />
              <xs:element name="aÃ±o" type="xs:unsignedShort" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sergiomateos1daw/LMSGI_UD4/CONCESIONARIO/CASO REAL/flexicarXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="flexicar.xsd">
    <coche>
        <codigo>0001</codigo>
        <marca>BMW</marca>
        <modelo>Serie 2</modelo>
        <potencia>1.500 / 140 cv</potencia>
        <kms>25807</kms>
        <plazas>5</plazas>
        <puertas>4</puertas>
        <año>2020</año>
    </coche>
    <coche>
        <codigo>0002</codigo>
        <marca>Audi</marca>
        <modelo>A7</modelo>
        <potencia>3.000 / 218 cv</potencia>
        <kms>0</kms>
        <plazas>4</plazas>
        <puertas>5</puertas>
        <año>2017</año>
    </coche>
    <coche>
        <codigo>0003</codigo>
        <marca>Nissan</marca>
        <modelo>Qashqai</modelo>
        <potencia>1.600 / 130 cv</potencia>
        <kms>65808 km</kms>
        <plazas>5</plazas>
        <puertas>5</puertas>
        <año>2017</año>
    </coche>
    <coche>
        <codigo>0004</codigo>
        <marca>SEAT</marca>
        <modelo>Ibiza</modelo>
        <potencia>1.000 / 80 cv</potencia>
        <kms>26600</kms>
        <plazas>5</plazas>
        <puertas>5</puertas>
        <año>2019</año>
    </coche>
</coches>
