=== sergiomateos1daw/LMSGI_UD4/CLIENTES/clientes.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT clientes (sede)+>
<!ATTLIST clientes
  xmlns CDATA #FIXED ''>

<!ELEMENT sede (direccion+,nombreEmpleado,fechaAlta,descripcionCliente,cliente+)>
<!ATTLIST sede
  xmlns CDATA #FIXED ''
  codigo NMTOKEN #REQUIRED>

<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion
  xmlns CDATA #FIXED ''>

<!ELEMENT nombreEmpleado (#PCDATA)>
<!ATTLIST nombreEmpleado
  xmlns CDATA #FIXED ''>

<!ELEMENT fechaAlta (#PCDATA)>
<!ATTLIST fechaAlta
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcionCliente (#PCDATA)>
<!ATTLIST descripcionCliente
  xmlns CDATA #FIXED ''>

<!ELEMENT cliente (numViviendas,resumenViviendas,plazoAlta)>
<!ATTLIST cliente
  xmlns CDATA #FIXED ''
  codigo NMTOKEN #REQUIRED>

<!ELEMENT numViviendas (costeVivienda)>
<!ATTLIST numViviendas
  xmlns CDATA #FIXED ''
  numero CDATA #REQUIRED>

<!ELEMENT resumenViviendas (#PCDATA)>
<!ATTLIST resumenViviendas
  xmlns CDATA #FIXED ''>

<!ELEMENT plazoAlta (#PCDATA)>
<!ATTLIST plazoAlta
  xmlns CDATA #FIXED ''>

<!ELEMENT costeVivienda (#PCDATA)>
<!ATTLIST costeVivienda
  xmlns CDATA #FIXED ''>

=== sergiomateos1daw/LMSGI_UD4/CLIENTES2/clientes_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="T12345BC">
        <direccion>Calle Larga</direccion>
        <direccion>Avenida Espa√±a 82</direccion>
        <nombreEmpleado>Sergio Mateos</nombreEmpleado>
        <fechaAlta>2022-02-01T00:00:00</fechaAlta>
        <descripcionCliente>Solvente</descripcionCliente>
        <cliente codigo="CCC-123">
            <numViviendas>2</numViviendas>
            <costeVivienda>13296</costeVivienda>
            <resumenViviendas>Resumen Vivienda</resumenViviendas>
            <plazoAlta>2022-01-22</plazoAlta>
        </cliente>
        <cliente codigo="ABC-234">
            <numViviendas>1</numViviendas>
            <costeVivienda>4000</costeVivienda>
            <resumenViviendas>Como nueva</resumenViviendas>
            <plazoAlta>2022-01-23</plazoAlta>
        </cliente>
    </sede>
    <sede codigo="A12345MN">
        <direccion>Ubrique Avenida Jose Maria 12</direccion>
        <nombreEmpleado>Anotio Juan Rios</nombreEmpleado>
        <fechaAlta>2022-02-04T12:00:00</fechaAlta>
        <descripcionCliente>Insolvente</descripcionCliente>
        <cliente codigo="TYU-679">
            <numViviendas>1</numViviendas>
            <costeVivienda>1000</costeVivienda>
            <resumenViviendas>Mal estado</resumenViviendas>
            <plazoAlta>2022-02-10</plazoAlta>
        </cliente>
    </sede>
</clientes>
