=== sergiomateos1daw/LMSGI_UD4/CLIENTES/CASO REAL/clientesReal.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
    <xs:documentation xml:lang="Es-es">
      Esquema para alta de clientes en sede central
      <fecha>31/01/2022</fecha>
      <autor>Sergio Mateos Puerta</autor>
    </xs:documentation>
  </xs:annotation>
<xs:element name="clientes">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="sede" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:string" name="direccion" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="xs:string" name="nombreEmpleado"/>
            <xs:element type="xs:dateTime" name="fechaAlta"/>
            <xs:element type="xs:string" name="descripcionCliente"/>
            <xs:element name="cliente">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="vivienda" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="numViviendas">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:string">
                                <xs:attribute type="xs:byte" name="numero" use="optional"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element type="xs:int" name="costeVivienda"/>
                        <xs:element type="xs:byte" name="numHabitaciones"/>
                        <xs:element type="xs:string" name="resumenViviendas"/>
                        <xs:element type="xs:date" name="plazoAlta"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute type="xs:string" name="codigo" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="codigo" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== sergiomateos1daw/LMSGI_UD4/CLIENTES/CASO REAL/clientesReal_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientesReal.xsd">
    <sede codigo="T45678XV">
        <direccion>Calle Avenida de Epa√±a 82</direccion>
        <direccion>Calle San Ignacio 23-C</direccion>
        <nombreEmpleado>Serigo Mateos Puerta</nombreEmpleado>
        <fechaAlta>2021-01-01T00:00:00</fechaAlta>
        <descripcionCliente>Solvente</descripcionCliente>
        <cliente codigo="THB-123">
            <vivienda>
                <numViviendas numero="1"></numViviendas>
                <costeVivienda>139656</costeVivienda>
                <numHabitaciones>5</numHabitaciones>
                <resumenViviendas>Vacia</resumenViviendas>
                <plazoAlta>2022-01-14</plazoAlta>
            </vivienda>
        </cliente>
    </sede>
    <sede codigo="P47923YU">
        <direccion>Direccion de la sede</direccion>
        <nombreEmpleado>Antoni Juan Rios</nombreEmpleado>
        <fechaAlta>2022-01-21T14:30:00</fechaAlta>
        <descripcionCliente>Insolvente</descripcionCliente>
        <cliente codigo="THB-123">
            <vivienda>
                <numViviendas numero="1"></numViviendas>
                <costeVivienda>139656</costeVivienda>
                <numHabitaciones>5</numHabitaciones>
                <resumenViviendas>Vacia</resumenViviendas>
                <plazoAlta>2022-01-14</plazoAlta>
            </vivienda>
            <vivienda>
                <numViviendas numero="2"></numViviendas>
                <costeVivienda>16395</costeVivienda>
                <numHabitaciones>2</numHabitaciones>
                <resumenViviendas>En buen estado</resumenViviendas>
                <plazoAlta>2021-03-18</plazoAlta>
            </vivienda>
        </cliente>
    </sede>
</clientes>
